version: '3.8'

services:
  web:
    image: mcr.microsoft.com/dotnet/sdk:8.0  
    container_name: dotnet_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
    ports:
      - "5000:5000"  
    working_dir: /app
    command: dotnet run


  angular-app:
    image: nginx:latest 
    container_name: angular_app
    ports:
      - "4200:4200" 
    volumes:
      - ./dist:/usr/share/nginx/html  
    restart: always  
